import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/global/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter.className} flex min-h-screen w-screen items-start justify-center relative`}
        >
          <Header />
          <section className="w-full h-full pt-20 from-blue-50 to-cyan-50 bg-gradient-to-r">
            {children}
          </section>
        </body>
      </html>
    </ClerkProvider>
  );
}
